---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: nextcloud-db
  namespace: nextcloud
spec:
  instances: 3
  imagePullPolicy: IfNotPresent
  storage:
    storageClass: ceph-block
    size: 5Gi
  monitoring:
    enablePodMonitor: true
